"""RiftX-owned Code Audit primitives."""

from .paths import (
    DEFAULT_MAX_REPOSITORY_FILTER_PATH_BYTES,
    DEFAULT_MAX_REPOSITORY_FILTER_PATHS,
    DEFAULT_MAX_REPOSITORY_FILTER_TOTAL_BYTES,
    DEFAULT_SOURCE_PATH_POLICY_VERSION,
    REPOSITORY_DESCRIPTOR_CHAIN_DIGEST_DOMAIN,
    REPOSITORY_IDENTITY_DIGEST_DOMAIN,
    SOURCE_ROOT_IDENTITY_DIGEST_DOMAIN,
    AuthorizedSourceRepository,
    RepositoryPathFilters,
    SourceDirectoryIdentity,
    SourcePathAuthorizationError,
    SourcePathFailure,
    open_authorized_source_repository,
    validate_posix_absolute_path,
    validate_repository_filters,
    validate_repository_relative_path,
    validate_repository_relative_paths,
)

__all__ = [
    "DEFAULT_MAX_REPOSITORY_FILTER_PATH_BYTES",
    "DEFAULT_MAX_REPOSITORY_FILTER_PATHS",
    "DEFAULT_MAX_REPOSITORY_FILTER_TOTAL_BYTES",
    "DEFAULT_SOURCE_PATH_POLICY_VERSION",
    "REPOSITORY_DESCRIPTOR_CHAIN_DIGEST_DOMAIN",
    "REPOSITORY_IDENTITY_DIGEST_DOMAIN",
    "SOURCE_ROOT_IDENTITY_DIGEST_DOMAIN",
    "AuthorizedSourceRepository",
    "RepositoryPathFilters",
    "SourceDirectoryIdentity",
    "SourcePathAuthorizationError",
    "SourcePathFailure",
    "open_authorized_source_repository",
    "validate_posix_absolute_path",
    "validate_repository_filters",
    "validate_repository_relative_path",
    "validate_repository_relative_paths",
]
