"""Historical snapshot primitives retained for Code Workspace compatibility."""

from .snapshot import (
    SNAPSHOT_CAS_INDEX_SCHEMA_VERSION,
    SNAPSHOT_CAS_OBJECT_SCHEMA_VERSION,
    SNAPSHOT_CONTENT_STORAGE_KEY_PREFIX,
    SNAPSHOT_MANIFEST_INDEX_NAME,
    SNAPSHOT_REFERENCE_SCHEMA_VERSION,
    SNAPSHOT_STORE_SCHEMA_VERSION,
    OpenedSnapshotBlob,
    SnapshotBlobMetadata,
    SnapshotBlobObjectType,
    SnapshotCASBinding,
    SnapshotCASDescriptor,
    SnapshotCASObjectType,
    SnapshotIntegrityResult,
    SnapshotReference,
    SnapshotReferenceRepository,
    SnapshotReferenceRole,
    SnapshotStagedTree,
    SnapshotStagingCleanupReceipt,
    SnapshotStore,
    SnapshotStoreCrash,
    SnapshotStoreError,
    SnapshotStoreFailure,
    StoredSnapshotTree,
    parse_snapshot_content_storage_key,
)
from .snapshot_store import LocalSnapshotStore, SnapshotBlobReader
from .snapshot_view import (
    LOCAL_SNAPSHOT_VIEW_SCHEMA_VERSION,
    LocalSnapshotView,
    LocalSnapshotViewEntry,
    LocalSnapshotViewError,
    LocalSnapshotViewFailure,
    LocalSnapshotViewSummary,
    open_local_snapshot_view,
)

__all__ = [
    "LOCAL_SNAPSHOT_VIEW_SCHEMA_VERSION",
    "SNAPSHOT_CAS_INDEX_SCHEMA_VERSION",
    "SNAPSHOT_CAS_OBJECT_SCHEMA_VERSION",
    "SNAPSHOT_CONTENT_STORAGE_KEY_PREFIX",
    "SNAPSHOT_MANIFEST_INDEX_NAME",
    "SNAPSHOT_REFERENCE_SCHEMA_VERSION",
    "SNAPSHOT_STORE_SCHEMA_VERSION",
    "LocalSnapshotStore",
    "LocalSnapshotView",
    "LocalSnapshotViewEntry",
    "LocalSnapshotViewError",
    "LocalSnapshotViewFailure",
    "LocalSnapshotViewSummary",
    "OpenedSnapshotBlob",
    "SnapshotBlobMetadata",
    "SnapshotBlobObjectType",
    "SnapshotBlobReader",
    "SnapshotCASBinding",
    "SnapshotCASDescriptor",
    "SnapshotCASObjectType",
    "SnapshotIntegrityResult",
    "SnapshotReference",
    "SnapshotReferenceRepository",
    "SnapshotReferenceRole",
    "SnapshotStagedTree",
    "SnapshotStagingCleanupReceipt",
    "SnapshotStore",
    "SnapshotStoreCrash",
    "SnapshotStoreError",
    "SnapshotStoreFailure",
    "StoredSnapshotTree",
    "open_local_snapshot_view",
    "parse_snapshot_content_storage_key",
]
