id: riftx-exposed-api

info:
  name: Exposed API Metadata
  author: riftx
  severity: info
  tags: exposure,riftx

http:
  - method: GET
    path:
      - "{{BaseURL}}/api-docs"
      - "{{BaseURL}}/swagger.json"
      - "{{BaseURL}}/rest/admin/application-configuration"
    stop-at-first-match: true
    matchers:
      - type: status
        status:
          - 200
