"""Canonical public-web acquisition and source registry."""

from .fetch import (
    ApplicationWebArtifactStore,
    PublicDestinationError,
    PublicWebFetcher,
    WebFetchError,
)
from .models import (
    CachePolicy,
    EvidenceSpan,
    ExtractionStatus,
    FetchRequest,
    FetchResult,
    FetchResultStatus,
    RedirectPolicy,
    SourceReference,
    SourceType,
    WebDestinationClass,
    WebDocument,
    WebDocumentChunk,
    WebSourceClass,
)
from .repository import WebSourceRepository
from .research import (
    UNTRUSTED_EXTERNAL_CONTENT,
    DeterministicFocusedExtractor,
    DeterministicQueryPlanner,
    PlannedSearchQuery,
    ResearchClaim,
    ResearchRequest,
    SearchPlan,
    SourceDisagreement,
    WebContextPack,
    WebExtractionRequest,
    WebResearchNote,
    WebResearchPacket,
    WebResearchPipeline,
    packet_to_context,
    rank_search_results,
)
from .search import (
    OpenAIHostedSearchProvider,
    SearchFreshness,
    SearchProvider,
    SearchProviderError,
    SearchRequest,
    SearchResponse,
    SearchResult,
    SearchType,
    SearXNGSearchProvider,
)

__all__ = [
    "ApplicationWebArtifactStore",
    "CachePolicy",
    "EvidenceSpan",
    "ExtractionStatus",
    "FetchRequest",
    "FetchResult",
    "FetchResultStatus",
    "PublicDestinationError",
    "PublicWebFetcher",
    "RedirectPolicy",
    "SourceReference",
    "SourceType",
    "OpenAIHostedSearchProvider",
    "SearchFreshness",
    "SearchProvider",
    "SearchProviderError",
    "SearchRequest",
    "SearchResponse",
    "SearchResult",
    "SearchType",
    "SearXNGSearchProvider",
    "WebDestinationClass",
    "WebDocument",
    "WebDocumentChunk",
    "WebFetchError",
    "WebSourceClass",
    "WebSourceRepository",
    "UNTRUSTED_EXTERNAL_CONTENT",
    "DeterministicFocusedExtractor",
    "DeterministicQueryPlanner",
    "PlannedSearchQuery",
    "ResearchClaim",
    "ResearchRequest",
    "SearchPlan",
    "SourceDisagreement",
    "WebContextPack",
    "WebExtractionRequest",
    "WebResearchNote",
    "WebResearchPacket",
    "WebResearchPipeline",
    "packet_to_context",
    "rank_search_results",
]
