"""Context compilation support and bounded Tool Result processing."""

from .artifacts import (
    ExecutionArtifactStore,
    SpilledArtifact,
    execution_artifact_uri,
    parse_execution_artifact_uri,
)
from .budget import (
    ContextBudgetResult,
    RequiredContextOverflowError,
    TokenBudgeter,
)
from .checkpoints import (
    CheckpointType,
    CompactionStage,
    ContextCheckpoint,
    compaction_stage_for_usage,
)
from .compiler import ContextCompiler, ContextManifestBuilder, ManifestingContextCompiler
from .inspector import ContextApplicationService
from .instructions import (
    StableInstructionLoadError,
    StableInstructionScope,
    StableInstructionSource,
)
from .items import (
    CONTEXT_LAYER_ORDER,
    ContextItem,
    ContextItemKind,
    ContextLayer,
    ContextSource,
    StaticContextSource,
)
from .manifest import (
    ContextCategory,
    ContextCategoryUsage,
    ContextCompilation,
    ContextCompilationRepository,
    ContextManifest,
    ContextUsageRecorder,
    usage_token_counts,
)
from .models import (
    ArtifactReadResult,
    OutputStream,
    ProcessedToolResult,
    RawArtifactReference,
    StreamPreview,
)
from .reducer import (
    DuplicateAttemptError,
    HypothesisEvidenceError,
    PlanRegressionError,
    WorkingMemoryReducer,
    WorkingMemoryReductionError,
    WorkingMemoryVersionConflict,
)
from .sources import (
    TranscriptContextSource,
    WorkingMemoryContextSource,
    processed_tool_result_context_item,
)
from .token_counter import estimate_context_tokens
from .tool_results import ToolResultProcessor
from .working_memory import (
    ActiveExecutionRef,
    ActiveTerminalRef,
    AttemptRecord,
    AttemptStatus,
    ConfirmedFact,
    CurrentFocus,
    EvidenceSource,
    FactCandidate,
    FactStatus,
    Hypothesis,
    HypothesisEvidenceEffect,
    HypothesisStatus,
    HypothesisUpdate,
    NextAction,
    PendingQuestion,
    PlanItem,
    PlanItemStatus,
    PlanItemUpdate,
    PlanUpdateProposal,
    RunPlan,
    UserDecision,
    WorkingMemory,
    WorkingMemoryRepository,
)

__all__ = [
    "CONTEXT_LAYER_ORDER",
    "ContextBudgetResult",
    "ContextCompiler",
    "ContextCheckpoint",
    "CheckpointType",
    "CompactionStage",
    "compaction_stage_for_usage",
    "ContextItem",
    "ContextItemKind",
    "ContextLayer",
    "ContextSource",
    "RequiredContextOverflowError",
    "StaticContextSource",
    "StableInstructionLoadError",
    "StableInstructionScope",
    "StableInstructionSource",
    "TokenBudgeter",
    "TranscriptContextSource",
    "WorkingMemoryContextSource",
    "ActiveExecutionRef",
    "ActiveTerminalRef",
    "AttemptRecord",
    "AttemptStatus",
    "ConfirmedFact",
    "CurrentFocus",
    "DuplicateAttemptError",
    "EvidenceSource",
    "FactCandidate",
    "FactStatus",
    "Hypothesis",
    "HypothesisEvidenceEffect",
    "HypothesisEvidenceError",
    "HypothesisStatus",
    "HypothesisUpdate",
    "NextAction",
    "PendingQuestion",
    "PlanItem",
    "PlanItemStatus",
    "PlanItemUpdate",
    "PlanRegressionError",
    "PlanUpdateProposal",
    "RunPlan",
    "UserDecision",
    "WorkingMemory",
    "WorkingMemoryReducer",
    "WorkingMemoryReductionError",
    "WorkingMemoryRepository",
    "WorkingMemoryVersionConflict",
    "ArtifactReadResult",
    "ContextApplicationService",
    "ContextCategory",
    "ContextCategoryUsage",
    "ContextCompilation",
    "ContextCompilationRepository",
    "ContextManifest",
    "ContextManifestBuilder",
    "ContextUsageRecorder",
    "ExecutionArtifactStore",
    "ManifestingContextCompiler",
    "OutputStream",
    "ProcessedToolResult",
    "RawArtifactReference",
    "SpilledArtifact",
    "StreamPreview",
    "ToolResultProcessor",
    "execution_artifact_uri",
    "estimate_context_tokens",
    "parse_execution_artifact_uri",
    "processed_tool_result_context_item",
    "usage_token_counts",
]
