//! Local-only RiftX daemon transport.

mod client;
mod endpoint;
mod listener;
mod protocol;

pub use client::LocalIpcClient;
pub use client::LocalIpcError;
pub use client::LocalIpcResponse;
pub use client::LocalSseEvent;
pub use client::LocalSseStream;
pub use endpoint::LocalIpcEndpoint;
pub use listener::LocalIpcListener;
pub use protocol::ApprovalDecision;
pub use protocol::ApprovalDecisionParams;
pub use protocol::ApprovalKind;
pub use protocol::Artifact;
pub use protocol::AssessmentObjective;
pub use protocol::AuditHealthState;
pub use protocol::AuditHealthStatus;
pub use protocol::AuthorizationScope;
pub use protocol::AuthorizationWindow;
pub use protocol::CaptureArtifactParams;
pub use protocol::ChangeModeParams;
pub use protocol::ConversationEntry;
pub use protocol::ConversationKind;
pub use protocol::ConversationPage;
pub use protocol::ConversationRole;
pub use protocol::CreateCredentialGrantParams;
pub use protocol::CreateCredentialReferenceParams;
pub use protocol::CreateEngagementParams;
pub use protocol::CredentialExecutionParams;
pub use protocol::CredentialExecutionResponse;
pub use protocol::CredentialGrant;
pub use protocol::CredentialGrantUse;
pub use protocol::CredentialKind;
pub use protocol::CredentialReference;
pub use protocol::CredentialUseStatus;
pub use protocol::CredentialUseTarget;
pub use protocol::DaemonControlStatus;
pub use protocol::DaemonInfo;
pub use protocol::DaemonPauseReason;
pub use protocol::DaemonRunState;
pub use protocol::DiscoveredSkill;
pub use protocol::DiscoveredTool;
pub use protocol::Engagement;
pub use protocol::EngagementEvent;
pub use protocol::EngagementReport;
pub use protocol::EngagementStatus;
pub use protocol::EnvironmentClass;
pub use protocol::Execution;
pub use protocol::ExecutionMode;
pub use protocol::ExtensionDiagnostic;
pub use protocol::ExtensionDiagnosticLevel;
pub use protocol::IPC_PROTOCOL_VERSION;
pub use protocol::IdentitySelector;
pub use protocol::LlmCapabilityCheck;
pub use protocol::LlmCapabilityMatrix;
pub use protocol::LlmCheckStatus;
pub use protocol::LlmConnectionTestResult;
pub use protocol::LlmProfileList;
pub use protocol::LlmProfileState;
pub use protocol::LlmProfileSummary;
pub use protocol::PendingApproval;
pub use protocol::ReportFormat;
pub use protocol::ReportSkill;
pub use protocol::ReportSkillSource;
pub use protocol::ReportTool;
pub use protocol::ReportToolRisk;
pub use protocol::Scope;
pub use protocol::SkillCatalog;
pub use protocol::SkillReportSnapshot;
pub use protocol::SkillSource;
pub use protocol::StartTurnParams;
pub use protocol::StructuredSuccessCriterion;
pub use protocol::TaskStatus;
pub use protocol::ToolCredentialInjection;
pub use protocol::ToolCredentialMetadata;
pub use protocol::ToolInventory;
pub use protocol::ToolMetadata;
pub use protocol::ToolReportSnapshot;
pub use protocol::ToolRisk;
pub use protocol::TurnAccepted;

#[cfg(test)]
#[path = "ipc_tests.rs"]
mod tests;
